# Generated by Django 5.2.15 on 2026-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundary_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarycsvproject',
            name='label_column_name',
            field=models.CharField(default='label', max_length=255),
        ),
    ]
